sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.5"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:

  - nosetests --processes=-1 --process-timeout=60 --process-restartworker

after_success:
  - coveralls